services:

  backend:

    build: .

    ports:
      - "8000:8000"

    volumes:
      - chroma_storage:/app/chroma_db

    env_file:
      - .env

  frontend:

    build: .

    command: streamlit run frontend.py --server.port 8501 --server.adress 0.0.0.0

    ports:
      - "8501:8501"

    depends_on:
      - backend

volumes:
  chroma_storage: