#week 19 project
# Semantic search engine(Top-k retrieval)

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

#Load model
model = SentenceTransformer("all-MiniLM-L6-v2")

#Knowledge base
documents = [
     "Artificial intelligence is transforming healthcare.",
    "Machine learning helps analyze large datasets.",
    "Space exploration requires advanced rocket science.",
    "Deep learning improves image recognition systems.",
    "Cooking requires proper heat and ingredients.",
    "Neural networks are inspired by the human brain.",
    "Data science combines statistics and programming.",
    "Airplanes fly using lift generated by wings.",
    "Medicine helps cure diseases and improve health.",
    "Programming is essential for building software."
]

# Convert docs into embeddings

